### ISSUE TITLE
Exception: aspmc.programs.program.UnsupportedException

### ISSUE THREAD

**Issue by mahi045** [raki123/aspmc#2]
I tried to count all answer sets of the following ASP program in ASP mode (it is the hamiltonian cycle problem):
```
% Generate
{ cycle(X,Y) : edge(X,Y) } = 1 :- node(X).
{ cycle(X,Y) : edge(X,Y) } = 1 :- node(Y).
% Define
reached(Y) :- cycle(1,Y).
reached(Y) :- cycle(X,Y), reached(X).
% Test
:- node(Y), not reached(Y).


% Nodes
node(1..6).
% (Directed) Edges
edge(1,(2;3;4)).  edge(2,(4;5;6)).  edge(3,(1;4;5)).
edge(4,(1;2)).    edge(5,(3;4;6)).  edge(6,(2;3;5)).
```  
However, aspmc gives the following exception. 
```
  raise UnsupportedException("Currently only no choice rules with more than one atom in the head are supported.")
aspmc.programs.program.UnsupportedException: Currently only no choice rules with more than one atom in the head are supported.
```
How do we count answer sets of these kinds of programs?
Thanks.

**Comment by raki123** [comment]
Thank you for your question.
aspmc currently only supports normal answer set programs (i.e. no aggregates, weight constraints, etc.), with the only exception being unconditional guesses, i.e., rules of the form 
```
{a}.
````
The generate part of your program makes use of features of ASP that do not fall into the fragment of normal programs.
However, there is an encoding of the Hamiltonian cycle problem into ASP that does not make use of these features.
E.g., for X = 1 given these input facts one could replace the rule 
```
{ cycle(X,Y) : edge(X,Y) } = 1 :- node(X).
```
by the rules
```
cycle(1, 2) :- not cycle(1,3), not cycle(1,4).
cycle(1, 3) :- not cycle(1,2), not cycle(1,4).
cycle(1, 4) :- not cycle(1,2), not cycle(1,3).
```
which are normal.
Generally recognizing programs, where such a translation is possible automatically is a lot of work and implementing it for special cases does not make sense to me. 
However, Tomi Janhunen has a library that supports rewriting of broad classes of non-normal programs to normal programs (in smodels format) [1][2].

While aspmc currently does not support parsing programs in smodels format, this is a feature that is not too hard to add and that I could add to aspmc if you are interested. Adding the translator directly to aspmc is not an option since it is available only under GPLv3 currently but aspmc also supports model counters/knowledge compilers that are not open source.

Let me know if you would be interested in smodels support.

[1] http://research.ics.aalto.fi/software/asp/lp2normal/
[2] https://github.com/tomijanhunen/asptranslate

**Comment by mahi045** [comment]
Thanks for your information.
I understand that I should use lp2normal tool.

**Comment by raki123** [comment]
Well, yes but lp2normal accepts and outputs programs in smodels format, rather than plain text format. 
I can add support for programs in smodels format to aspmc though. Until when would you need it?

**Comment by mahi045** [comment]
Thanks, it will be helpful if you add Smodels support. However, you can add this *anytime*. I do not need it urgently because I have already got things done.
Thanks for your information.

**Comment by raki123** [comment]
Ok good. I will let you know when it is done.

**Comment by raki123** [comment]
Smodels support was easier than expected. Both the version in git and the python package aspmc version 1.0.8 support smodels now, when used with `-m smodels`.
If you have any problems let me know.
