### ISSUE TITLE
Backdoor Computation techniques: Clingo vs FVS

### ISSUE THREAD

**Issue by mahi045** [raki123/aspmc#3]
The config.py says that cbs(.) is computed by [fvs](https://github.com/raki123/aspmc/blob/main/aspmc/config.py#L7)
May I know what are the differences between backdoor computation techniques employed by Clingo and fvs?

Thanks.

**Comment by raki123** [comment]
FVS is a c++ Library for computing Feedback vertex sets (which are backdoors in the sense of cbs). 
When using clingo as a strategy, we give clingo an encoding of the feedback vertex set Problem and let it solve. 
So both compute a Feedback vertex set. The main difference is that FVS is usually faster since it is specialized to the task.

**Comment by raki123** [comment]
The used version of FVS is here:
https://github.com/raki123/FeedbackVertexSet-Experiments
